apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: orbit-backend
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: orbit-frontend
spec:
  lookupPolicy:
    local: true
