apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: orbit-backend
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: orbit-backend:latest
  runPolicy: Serial
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: orbit-frontend
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: orbit-frontend:latest
  runPolicy: Serial
